// VARUNA — Language Context (EN / HI / MR)
import { createContext, useContext, useState } from 'react';

const translations = {
  en: {
    appName: 'VARUNA',
    tagline: 'Indian Naval Asset Locator',
    heroTitle: 'The Guardians of',
    heroTitleHighlight: 'Samudra',
    heroSubtitle: 'Tracking the might of the Indian Navy — from Nuclear Submarines to Aircraft Carriers. Aatmanirbhar. Agile. Unstoppable.',
    heroCta: 'Explore Indian Naval Fleet',
    heroScrollHint: 'Scroll to discover',
    statsTitle: 'Fleet at a Glance',
    statsSubtitle: 'The combined power of the Indian Navy and Coast Guard as of June 2026.',
    statsItems: {
      totalVessels: 'Total Vessels',
      activeWarships: 'Active Warships',
      personnel: 'Naval Personnel',
      nuclearSubs: 'Nuclear Submarines',
      conventionalSubs: 'Conventional Submarines',
      carriers: 'Aircraft Carriers',
      navalBases: 'Naval Bases',
      coastlineKm: 'Coastline (km)',
      eez: 'EEZ (sq km)',
      displacement: 'Total Displacement (tons)',
      range: 'Combined Range (km)',
      missiles: 'Missile Systems',
      torpedoes: 'Torpedo Tubes',
      aircraft: 'Aircraft in Service',
      icg: 'Coast Guard Vessels',
      indigenous: '% Indigenous Fleet',
      shipyards: 'Active Shipyards',
      projects: 'Projects Underway',
    },
    aatmanirbharTitle: "Aatmanirbhar Bharat —",
    aatmanirbharTitleHighlight: "Builder's Navy",
    aatmanirbharSubtitle: 'June 2026 Milestone',
    aatmanirbharDesc: "As of June 2026, the Indian Navy has transformed into a true 'Builder's Navy.' A record 67% of the fleet is now indigenously built, with 56 warship construction projects underway across 8 shipyards. The historic triple-commissioning on June 21, 2026, showcased India's industrial might.",
    tripleCommission: 'Triple Commissioning — 21 June 2026',
    tripleCommissionDesc: 'Three major warships commissioned in a single ceremony: INS Dunagiri (Frigate, Project 17A), INS Agray (ASW SWC), and INS Sanshodhak (Survey Vessel) — a first in Indian naval history.',
    historicTitle: 'Historic Fleet',
    historicSubtitle: 'The legends that built a Navy.',
    exploreTitle: 'Indian Naval Fleet',
    exploreSubtitle: 'Browse the complete Order of Battle of the Indian Navy and Coast Guard.',
    searchPlaceholder: 'Search by name, class, or project...',
    viewDetails: 'View Details',
    commissioned: 'Commissioned',
    decommissioned: 'Decommissioned',
    status: 'Status',
    active: 'Active',
    decommissionedStatus: 'Decommissioned',
    category: 'Category',
    class: 'Class',
    project: 'Project',
    builder: 'Builder',
    origin: 'Origin',
    fleet: 'Fleet',
    homePort: 'Home Port',
    technicalSpecs: 'Technical Specifications',
    displacement: 'Displacement',
    length: 'Length',
    beam: 'Beam',
    draft: 'Draft',
    speed: 'Top Speed',
    range: 'Range',
    crew: 'Crew',
    propulsion: 'Propulsion',
    armament: 'Armament',
    aircraft: 'Aircraft',
    sensors: 'Sensors',
    operationalHistory: 'Operational History',
    watchVideo: 'Watch Video',
    backToFleet: 'Back to Fleet',
    noResults: 'No assets found for this filter.',
    footerTagline: 'Tracking the Indian Navy — Jai Hind!',
    navExplore: 'Explore Fleet',
    navHistoric: 'Historic',
    navAbout: 'About',
    pennant: 'Pennant',
  },

  hi: {
    appName: 'वरुण',
    tagline: 'भारतीय नौसेना संपत्ति लोकेटर',
    heroTitle: 'समुद्र के',
    heroTitleHighlight: 'रक्षक',
    heroSubtitle: 'भारतीय नौसेना की शक्ति को ट्रैक करें — परमाणु पनडुब्बियों से लेकर विमानवाहक पोतों तक। आत्मनिर्भर। चुस्त। अजेय।',
    heroCta: 'भारतीय नौसेना बेड़े का अन्वेषण करें',
    heroScrollHint: 'स्क्रॉल करके जानें',
    statsTitle: 'बेड़े की एक झलक',
    statsSubtitle: 'जून 2026 तक भारतीय नौसेना और तटरक्षक बल की संयुक्त शक्ति।',
    statsItems: {
      totalVessels: 'कुल जहाज',
      activeWarships: 'सक्रिय युद्धपोत',
      personnel: 'नौसेना कर्मी',
      nuclearSubs: 'परमाणु पनडुब्बियाँ',
      conventionalSubs: 'पारंपरिक पनडुब्बियाँ',
      carriers: 'विमानवाहक पोत',
      navalBases: 'नौसेना बेस',
      coastlineKm: 'तटरेखा (किमी)',
      eez: 'ईईजेड (वर्ग किमी)',
      displacement: 'कुल विस्थापन (टन)',
      range: 'संयुक्त परास (किमी)',
      missiles: 'मिसाइल प्रणालियाँ',
      torpedoes: 'टॉर्पीडो ट्यूब',
      aircraft: 'सेवा में विमान',
      icg: 'तटरक्षक जहाज',
      indigenous: '% स्वदेशी बेड़ा',
      shipyards: 'सक्रिय शिपयार्ड',
      projects: 'जारी परियोजनाएं',
    },
    aatmanirbharTitle: 'आत्मनिर्भर भारत —',
    aatmanirbharTitleHighlight: 'निर्माता की नौसेना',
    aatmanirbharSubtitle: 'जून 2026 मील का पत्थर',
    aatmanirbharDesc: 'जून 2026 तक, भारतीय नौसेना एक सच्ची \'निर्माता नौसेना\' में बदल गई है। बेड़े का रिकॉर्ड 67% अब स्वदेशी निर्मित है, जिसमें 8 शिपयार्डों में 56 युद्धपोत निर्माण परियोजनाएं चल रही हैं।',
    tripleCommission: 'तिहरा कमीशन — 21 जून 2026',
    tripleCommissionDesc: 'एक समारोह में तीन प्रमुख युद्धपोत कमीशन: आईएनएस दुनागिरी, आईएनएस अग्रे, और आईएनएस संशोधक।',
    historicTitle: 'ऐतिहासिक बेड़ा',
    historicSubtitle: 'वे दिग्गज जिन्होंने एक नौसेना बनाई।',
    exploreTitle: 'भारतीय नौसेना बेड़ा',
    exploreSubtitle: 'भारतीय नौसेना और तटरक्षक बल की संपूर्ण ऑर्डर ऑफ बैटल को ब्राउज़ करें।',
    searchPlaceholder: 'नाम, वर्ग, या परियोजना द्वारा खोजें...',
    viewDetails: 'विवरण देखें',
    commissioned: 'कमीशन',
    decommissioned: 'सेवामुक्त',
    status: 'स्थिति',
    active: 'सक्रिय',
    decommissionedStatus: 'सेवामुक्त',
    category: 'श्रेणी',
    class: 'वर्ग',
    project: 'परियोजना',
    builder: 'निर्माता',
    origin: 'मूल',
    fleet: 'बेड़ा',
    homePort: 'गृह बंदरगाह',
    technicalSpecs: 'तकनीकी विशिष्टताएं',
    displacement: 'विस्थापन',
    length: 'लंबाई',
    beam: 'बीम',
    draft: 'ड्राफ्ट',
    speed: 'अधिकतम गति',
    range: 'परास',
    crew: 'चालक दल',
    propulsion: 'प्रणोदन',
    armament: 'हथियार',
    aircraft: 'विमान',
    sensors: 'सेंसर',
    operationalHistory: 'परिचालन इतिहास',
    watchVideo: 'वीडियो देखें',
    backToFleet: 'बेड़े पर वापस',
    noResults: 'इस फ़िल्टर के लिए कोई संपत्ति नहीं मिली।',
    footerTagline: 'भारतीय नौसेना को ट्रैक करना — जय हिन्द!',
    navExplore: 'बेड़ा अन्वेषण',
    navHistoric: 'ऐतिहासिक',
    navAbout: 'के बारे में',
    pennant: 'पेनेंट',
  },

  mr: {
    appName: 'वरुण',
    tagline: 'भारतीय नौदल मालमत्ता लोकेटर',
    heroTitle: 'समुद्राचे',
    heroTitleHighlight: 'रक्षक',
    heroSubtitle: 'भारतीय नौदलाची शक्ती ट्रॅक करा — अण्वस्त्र पाणबुड्यांपासून विमानवाहू जहाजांपर्यंत। आत्मनिर्भर। चपळ। अजिंक्य।',
    heroCta: 'भारतीय नौदल ताफा एक्सप्लोर करा',
    heroScrollHint: 'स्क्रोल करा',
    statsTitle: 'ताफ्याचा आढावा',
    statsSubtitle: 'जून 2026 पर्यंत भारतीय नौदल आणि तटरक्षक दलाची एकत्रित शक्ती।',
    statsItems: {
      totalVessels: 'एकूण जहाजे',
      activeWarships: 'सक्रिय युद्धनौका',
      personnel: 'नौदल कर्मचारी',
      nuclearSubs: 'अण्वस्त्र पाणबुड्या',
      conventionalSubs: 'पारंपारिक पाणबुड्या',
      carriers: 'विमानवाहू जहाजे',
      navalBases: 'नौदल तळ',
      coastlineKm: 'किनारपट्टी (किमी)',
      eez: 'ईईझेड (चौ किमी)',
      displacement: 'एकूण विस्थापन (टन)',
      range: 'एकत्रित परास (किमी)',
      missiles: 'क्षेपणास्त्र प्रणाली',
      torpedoes: 'टॉर्पेडो नळ्या',
      aircraft: 'सेवेतील विमाने',
      icg: 'तटरक्षक जहाजे',
      indigenous: '% स्वदेशी ताफा',
      shipyards: 'सक्रिय जहाज कारखाने',
      projects: 'चालू प्रकल्प',
    },
    aatmanirbharTitle: 'आत्मनिर्भर भारत —',
    aatmanirbharTitleHighlight: 'निर्माणकर्त्याचे नौदल',
    aatmanirbharSubtitle: 'जून 2026 महत्त्वाचा टप्पा',
    aatmanirbharDesc: 'जून 2026 पर्यंत, भारतीय नौदल खऱ्या अर्थाने \'निर्माणकर्त्याचे नौदल\' बनले आहे। ताफ्यातील विक्रमी 67% आता स्वदेशी बांधणीचे आहे, 8 जहाज कारखान्यांमध्ये 56 युद्धनौका बांधणी प्रकल्प सुरू आहेत।',
    tripleCommission: 'त्रिविध कमिशनिंग — 21 जून 2026',
    tripleCommissionDesc: 'एकाच समारंभात तीन प्रमुख युद्धनौका कमिशन: INS दुनागिरी, INS अग्रे, आणि INS संशोधक।',
    historicTitle: 'ऐतिहासिक ताफा',
    historicSubtitle: 'ज्यांनी नौदल घडवले ते दिग्गज।',
    exploreTitle: 'भारतीय नौदल ताफा',
    exploreSubtitle: 'भारतीय नौदल आणि तटरक्षक दलाचा संपूर्ण ऑर्डर ऑफ बॅटल ब्राउझ करा।',
    searchPlaceholder: 'नाव, वर्ग किंवा प्रकल्पानुसार शोधा...',
    viewDetails: 'तपशील पहा',
    commissioned: 'कमिशन',
    decommissioned: 'सेवामुक्त',
    status: 'स्थिती',
    active: 'सक्रिय',
    decommissionedStatus: 'सेवामुक्त',
    category: 'श्रेणी',
    class: 'वर्ग',
    project: 'प्रकल्प',
    builder: 'बांधणीदार',
    origin: 'मूळ',
    fleet: 'ताफा',
    homePort: 'गृह बंदर',
    technicalSpecs: 'तांत्रिक वैशिष्ट्ये',
    displacement: 'विस्थापन',
    length: 'लांबी',
    beam: 'रुंदी',
    draft: 'खोली',
    speed: 'कमाल वेग',
    range: 'परास',
    crew: 'चालक दल',
    propulsion: 'प्रणोदन',
    armament: 'शस्त्रास्त्रे',
    aircraft: 'विमाने',
    sensors: 'सेन्सर',
    operationalHistory: 'परिचालन इतिहास',
    watchVideo: 'व्हिडिओ पहा',
    backToFleet: 'ताफ्याकडे परत',
    noResults: 'या फिल्टरसाठी कोणतीही मालमत्ता आढळली नाही।',
    footerTagline: 'भारतीय नौदल ट्रॅकिंग — जय हिंद!',
    navExplore: 'ताफा एक्सप्लोर',
    navHistoric: 'ऐतिहासिक',
    navAbout: 'बद्दल',
    pennant: 'पेनेंट',
  },
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState('en');
  const t = translations[lang];
  return (
    <LanguageContext.Provider value={{ lang, setLang, t, translations }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
}

export default LanguageContext;
