// VARUNA — Language Context (EN / HI / MR)
import { createContext, useContext, useEffect, useState } from 'react';

const translations = {
  en: {
    appName: 'VARUNA',
    tagline: 'Indian Naval Asset Locator',
    heroTitle: 'The Guardians of',
    heroTitleHighlight: 'Samudra',
    heroSubtitle: 'Tracking the might of the Indian Navy — from Nuclear Submarines to Aircraft Carriers. Aatmanirbhar. Agile. Unstoppable.',
    heroCta: 'Explore Indian Naval Fleet',
    heroScrollHint: 'Scroll to discover',
    statsTitle: 'Fleet at a Glance',
    statsSubtitle: 'The combined power of the Indian Navy and Coast Guard as of June 2026.',
    statsItems: {
      totalVessels: 'Total Vessels',
      activeWarships: 'Active Warships',
      personnel: 'Naval Personnel',
      nuclearSubs: 'Nuclear Submarines',
      conventionalSubs: 'Conventional Submarines',
      carriers: 'Aircraft Carriers',
      navalBases: 'Naval Bases',
      coastlineKm: 'Coastline (km)',
      eez: 'EEZ (sq km)',
      displacement: 'Total Displacement (tons)',
      range: 'Combined Range (km)',
      missiles: 'Missile Systems',
      torpedoes: 'Torpedo Tubes',
      aircraft: 'Aircraft in Service',
      icg: 'Coast Guard Vessels',
      indigenous: '% Indigenous Fleet',
      shipyards: 'Active Shipyards',
      projects: 'Projects Underway',
    },
    aatmanirbharTitle: "Aatmanirbhar Bharat —",
    aatmanirbharTitleHighlight: "Builder's Navy",
    aatmanirbharSubtitle: 'June 2026 Milestone',
    aatmanirbharDesc: "As of June 2026, the Indian Navy has transformed into a true 'Builder's Navy.' A record 67% of the fleet is now indigenously built, with 56 warship construction projects underway across 8 shipyards. The historic triple-commissioning on June 21, 2026, showcased India's industrial might.",
    tripleCommission: 'Triple Commissioning — 21 June 2026',
    tripleCommissionDesc: 'Three major warships commissioned in a single ceremony: INS Dunagiri (Frigate, Project 17A), INS Agray (ASW SWC), and INS Sanshodhak (Survey Vessel) — a first in Indian naval history.',
    historicTitle: 'Historic Fleet',
    historicSubtitle: 'The legends that built a Navy.',
    exploreTitle: 'Indian Naval Fleet',
    exploreSubtitle: 'Browse the complete Order of Battle of the Indian Navy and Coast Guard.',
    searchPlaceholder: 'Search by name, class, or project...',
    viewDetails: 'View Details',
    commissioned: 'Commissioned',
    decommissioned: 'Decommissioned',
    status: 'Status',
    active: 'Active',
    decommissionedStatus: 'Decommissioned',
    category: 'Category',
    class: 'Class',
    project: 'Project',
    builder: 'Builder',
    origin: 'Origin',
    fleet: 'Fleet',
    homePort: 'Home Port',
    technicalSpecs: 'Technical Specifications',
    displacement: 'Displacement',
    length: 'Length',
    beam: 'Beam',
    draft: 'Draft',
    speed: 'Top Speed',
    range: 'Range',
    crew: 'Crew',
    propulsion: 'Propulsion',
    armament: 'Armament',
    aircraft: 'Aircraft',
    sensors: 'Sensors',
    operationalHistory: 'Operational History',
    watchVideo: 'Watch Video',
    backToFleet: 'Back to Fleet',
    noResults: 'No assets found for this filter.',
    footerTagline: 'Tracking the Indian Navy — Jai Hind!',
    navExplore: 'Explore Fleet',
    navHistoric: 'Historic',
    navAbout: 'About',
    pennant: 'Pennant',
    navHome: 'Home',
    officialSite: 'Official Site',
    orderOfBattle: 'Indian Naval Order of Battle',
    exploreFleet: 'Explore the Fleet',
    scroll: 'Scroll',
    aboutEyebrow: 'About the Indian Navy',
    aboutTitle: 'Strength at Sea,',
    aboutTitleHighlight: 'Pride of a Nation',
    aboutPara1: 'The Indian Navy is the maritime branch of the Indian Armed Forces. With roots dating to the 17th-century Maratha Navy, it has evolved into one of the most powerful blue-water navies in the world, ranked among the top 10 globally.',
    aboutPara2: "Headquartered in New Delhi, the Navy operates three commands — Western (Mumbai), Eastern (Visakhapatnam), and Southern (Kochi) — responsible for securing India's vast maritime interests and the safety of millions of seafarers who transit the Indian Ocean.",
    aboutPara3Prefix: 'Under the',
    aboutPara3Strong: 'Aatmanirbhar Bharat',
    aboutPara3Suffix: 'initiative, India is transforming into a major naval manufacturing hub, commissioning indigenously built carriers, destroyers, frigates, and submarines at an unprecedented pace.',
    officialNavyWebsite: 'Official Indian Navy Website',
    browseFleet: 'Browse Fleet',
    legacyHeritage: 'Legacy & Heritage',
    viewAllHistoricAssets: 'View All Historic Assets',
    pillars: {
      maritimeTitle: 'Maritime Security',
      maritimeDesc: 'Safeguarding over 7,500 km of coastline and an Exclusive Economic Zone of 2.3 million sq km across the Indian Ocean Region.',
      powerTitle: 'Power Projection',
      powerDesc: 'Sustained blue-water capability with aircraft carriers, nuclear submarines, and a rapidly modernising surface fleet.',
      selfRelianceTitle: 'Aatmanirbhar Bharat',
      selfRelianceDesc: '67% of the fleet is now indigenously built, with over 56 shipbuilding projects underway across 8 active shipyards.',
      humanitarianTitle: 'Humanitarian Operations',
      humanitarianDesc: 'From disaster relief (Operation Kaveri, HADR) to anti-piracy patrols in the Gulf of Aden — the Navy serves beyond war.',
    },
    categoryLabels: {
      all: 'All Assets',
      carriers: 'Aircraft Carriers',
      destroyers: 'Destroyers',
      frigates: 'Frigates',
      corvettes: 'Corvettes & ASW',
      submarines: 'Submarines',
      amphibious: 'Amphibious',
      icg: 'Coast Guard',
      mpv: 'MPV & Support',
      survey: 'Survey & Replenishment',
      historic: 'Historic Fleet',
    },
    assetCountSingular: 'asset',
    assetCountPlural: 'assets',
    resultsFor: 'Results for',
    tryDifferentFilter: 'Try a different category or search term.',
    clearFilters: 'Clear filters',
    assetNotFound: 'Asset Not Found',
    returnToFleet: 'Return to Fleet',
    imageGallery: 'Image Gallery',
    officialVideo: 'Official Video',
    relatedAssets: 'Related Assets',
    speedLabel: 'Speed',
    crewLabel: 'Crew',
    navFooterTitle: 'Navigation',
    dataSources: 'Data Sources',
    home: 'Home',
    publicData: 'Public domain & open-source data',
    dataCurrent: 'Data current as of June 2026',
    footerDescription: 'A comprehensive open-source reference database of Indian Naval assets — warships, submarines, aircraft, and historic vessels.',
    footerLegal: 'For educational and reference purposes only. Not affiliated with the Indian Navy.',
    fleetOperational: 'FLEET OPERATIONAL',
  },

  hi: {
    appName: 'वरुण',
    tagline: 'भारतीय नौसेना संपत्ति लोकेटर',
    heroTitle: 'समुद्र के',
    heroTitleHighlight: 'रक्षक',
    heroSubtitle: 'भारतीय नौसेना की शक्ति को ट्रैक करें — परमाणु पनडुब्बियों से लेकर विमानवाहक पोतों तक। आत्मनिर्भर। चुस्त। अजेय।',
    heroCta: 'भारतीय नौसेना बेड़े का अन्वेषण करें',
    heroScrollHint: 'स्क्रॉल करके जानें',
    statsTitle: 'बेड़े की एक झलक',
    statsSubtitle: 'जून 2026 तक भारतीय नौसेना और तटरक्षक बल की संयुक्त शक्ति।',
    statsItems: {
      totalVessels: 'कुल जहाज',
      activeWarships: 'सक्रिय युद्धपोत',
      personnel: 'नौसेना कर्मी',
      nuclearSubs: 'परमाणु पनडुब्बियाँ',
      conventionalSubs: 'पारंपरिक पनडुब्बियाँ',
      carriers: 'विमानवाहक पोत',
      navalBases: 'नौसेना बेस',
      coastlineKm: 'तटरेखा (किमी)',
      eez: 'ईईजेड (वर्ग किमी)',
      displacement: 'कुल विस्थापन (टन)',
      range: 'संयुक्त परास (किमी)',
      missiles: 'मिसाइल प्रणालियाँ',
      torpedoes: 'टॉर्पीडो ट्यूब',
      aircraft: 'सेवा में विमान',
      icg: 'तटरक्षक जहाज',
      indigenous: '% स्वदेशी बेड़ा',
      shipyards: 'सक्रिय शिपयार्ड',
      projects: 'जारी परियोजनाएं',
    },
    aatmanirbharTitle: 'आत्मनिर्भर भारत —',
    aatmanirbharTitleHighlight: 'निर्माता की नौसेना',
    aatmanirbharSubtitle: 'जून 2026 मील का पत्थर',
    aatmanirbharDesc: 'जून 2026 तक, भारतीय नौसेना एक सच्ची \'निर्माता नौसेना\' में बदल गई है। बेड़े का रिकॉर्ड 67% अब स्वदेशी निर्मित है, जिसमें 8 शिपयार्डों में 56 युद्धपोत निर्माण परियोजनाएं चल रही हैं।',
    tripleCommission: 'तिहरा कमीशन — 21 जून 2026',
    tripleCommissionDesc: 'एक समारोह में तीन प्रमुख युद्धपोत कमीशन: आईएनएस दुनागिरी, आईएनएस अग्रे, और आईएनएस संशोधक।',
    historicTitle: 'ऐतिहासिक बेड़ा',
    historicSubtitle: 'वे दिग्गज जिन्होंने एक नौसेना बनाई।',
    exploreTitle: 'भारतीय नौसेना बेड़ा',
    exploreSubtitle: 'भारतीय नौसेना और तटरक्षक बल की संपूर्ण ऑर्डर ऑफ बैटल को ब्राउज़ करें।',
    searchPlaceholder: 'नाम, वर्ग, या परियोजना द्वारा खोजें...',
    viewDetails: 'विवरण देखें',
    commissioned: 'कमीशन',
    decommissioned: 'सेवामुक्त',
    status: 'स्थिति',
    active: 'सक्रिय',
    decommissionedStatus: 'सेवामुक्त',
    category: 'श्रेणी',
    class: 'वर्ग',
    project: 'परियोजना',
    builder: 'निर्माता',
    origin: 'मूल',
    fleet: 'बेड़ा',
    homePort: 'गृह बंदरगाह',
    technicalSpecs: 'तकनीकी विशिष्टताएं',
    displacement: 'विस्थापन',
    length: 'लंबाई',
    beam: 'बीम',
    draft: 'ड्राफ्ट',
    speed: 'अधिकतम गति',
    range: 'परास',
    crew: 'चालक दल',
    propulsion: 'प्रणोदन',
    armament: 'हथियार',
    aircraft: 'विमान',
    sensors: 'सेंसर',
    operationalHistory: 'परिचालन इतिहास',
    watchVideo: 'वीडियो देखें',
    backToFleet: 'बेड़े पर वापस',
    noResults: 'इस फ़िल्टर के लिए कोई संपत्ति नहीं मिली।',
    footerTagline: 'भारतीय नौसेना को ट्रैक करना — जय हिन्द!',
    navExplore: 'बेड़ा अन्वेषण',
    navHistoric: 'ऐतिहासिक',
    navAbout: 'के बारे में',
    pennant: 'पेनेंट',
    navHome: 'होम',
    officialSite: 'आधिकारिक साइट',
    orderOfBattle: 'भारतीय नौसेना ऑर्डर ऑफ बैटल',
    exploreFleet: 'बेड़े को देखें',
    scroll: 'स्क्रॉल',
    aboutEyebrow: 'भारतीय नौसेना के बारे में',
    aboutTitle: 'समुद्र में शक्ति,',
    aboutTitleHighlight: 'राष्ट्र का गर्व',
    aboutPara1: 'भारतीय नौसेना भारतीय सशस्त्र बलों की समुद्री शाखा है। 17वीं सदी की मराठा नौसेना से जुड़ी विरासत के साथ, यह दुनिया की सबसे सक्षम ब्लू-वॉटर नौसेनाओं में से एक बन चुकी है।',
    aboutPara2: 'नई दिल्ली में मुख्यालय वाली नौसेना तीन कमानों — पश्चिमी, पूर्वी और दक्षिणी — के माध्यम से भारत के विशाल समुद्री हितों की रक्षा करती है।',
    aboutPara3Prefix: 'के तहत',
    aboutPara3Strong: 'आत्मनिर्भर भारत',
    aboutPara3Suffix: 'पहल से भारत स्वदेशी विमानवाहक पोतों, विध्वंसकों, फ्रिगेटों और पनडुब्बियों के निर्माण वाला प्रमुख नौसैनिक विनिर्माण केंद्र बन रहा है।',
    officialNavyWebsite: 'भारतीय नौसेना की आधिकारिक वेबसाइट',
    browseFleet: 'बेड़ा ब्राउज़ करें',
    legacyHeritage: 'विरासत और इतिहास',
    viewAllHistoricAssets: 'सभी ऐतिहासिक संपत्तियां देखें',
    pillars: {
      maritimeTitle: 'समुद्री सुरक्षा',
      maritimeDesc: 'भारतीय महासागर क्षेत्र में 7,500 किमी से अधिक तटरेखा और विशाल विशेष आर्थिक क्षेत्र की सुरक्षा।',
      powerTitle: 'शक्ति प्रदर्शन',
      powerDesc: 'विमानवाहक पोतों, परमाणु पनडुब्बियों और आधुनिक सतही बेड़े के साथ मजबूत ब्लू-वॉटर क्षमता।',
      selfRelianceTitle: 'आत्मनिर्भर भारत',
      selfRelianceDesc: 'बेड़े का बड़ा हिस्सा स्वदेशी रूप से निर्मित है और कई युद्धपोत परियोजनाएं सक्रिय शिपयार्डों में चल रही हैं।',
      humanitarianTitle: 'मानवीय अभियान',
      humanitarianDesc: 'आपदा राहत से लेकर एंटी-पाइरेसी गश्त तक, नौसेना युद्ध से परे भी सेवा करती है।',
    },
    categoryLabels: {
      all: 'सभी संपत्तियां',
      carriers: 'विमानवाहक पोत',
      destroyers: 'विध्वंसक',
      frigates: 'फ्रिगेट',
      corvettes: 'कॉर्वेट और ASW',
      submarines: 'पनडुब्बियां',
      amphibious: 'उभयचर',
      icg: 'तटरक्षक',
      mpv: 'MPV और सपोर्ट',
      survey: 'सर्वे और पुनःपूर्ति',
      historic: 'ऐतिहासिक बेड़ा',
    },
    assetCountSingular: 'संपत्ति',
    assetCountPlural: 'संपत्तियां',
    resultsFor: 'परिणाम',
    tryDifferentFilter: 'कृपया अलग श्रेणी या खोज शब्द आज़माएं।',
    clearFilters: 'फ़िल्टर साफ़ करें',
    assetNotFound: 'संपत्ति नहीं मिली',
    returnToFleet: 'बेड़े पर वापस जाएं',
    imageGallery: 'छवि गैलरी',
    officialVideo: 'आधिकारिक वीडियो',
    relatedAssets: 'संबंधित संपत्तियां',
    speedLabel: 'गति',
    crewLabel: 'दल',
    navFooterTitle: 'नेविगेशन',
    dataSources: 'डेटा स्रोत',
    home: 'होम',
    publicData: 'सार्वजनिक और ओपन-सोर्स डेटा',
    dataCurrent: 'डेटा जून 2026 तक अद्यतन',
    footerDescription: 'भारतीय नौसैनिक संपत्तियों — युद्धपोतों, पनडुब्बियों, विमानों और ऐतिहासिक जहाजों — का संदर्भ डेटाबेस।',
    footerLegal: 'केवल शैक्षिक और संदर्भ उपयोग के लिए। भारतीय नौसेना से संबद्ध नहीं।',
    fleetOperational: 'बेड़ा परिचालन में',
  },

  mr: {
    appName: 'वरुण',
    tagline: 'भारतीय नौदल मालमत्ता लोकेटर',
    heroTitle: 'समुद्राचे',
    heroTitleHighlight: 'रक्षक',
    heroSubtitle: 'भारतीय नौदलाची शक्ती ट्रॅक करा — अण्वस्त्र पाणबुड्यांपासून विमानवाहू जहाजांपर्यंत। आत्मनिर्भर। चपळ। अजिंक्य।',
    heroCta: 'भारतीय नौदल ताफा एक्सप्लोर करा',
    heroScrollHint: 'स्क्रोल करा',
    statsTitle: 'ताफ्याचा आढावा',
    statsSubtitle: 'जून 2026 पर्यंत भारतीय नौदल आणि तटरक्षक दलाची एकत्रित शक्ती।',
    statsItems: {
      totalVessels: 'एकूण जहाजे',
      activeWarships: 'सक्रिय युद्धनौका',
      personnel: 'नौदल कर्मचारी',
      nuclearSubs: 'अण्वस्त्र पाणबुड्या',
      conventionalSubs: 'पारंपारिक पाणबुड्या',
      carriers: 'विमानवाहू जहाजे',
      navalBases: 'नौदल तळ',
      coastlineKm: 'किनारपट्टी (किमी)',
      eez: 'ईईझेड (चौ किमी)',
      displacement: 'एकूण विस्थापन (टन)',
      range: 'एकत्रित परास (किमी)',
      missiles: 'क्षेपणास्त्र प्रणाली',
      torpedoes: 'टॉर्पेडो नळ्या',
      aircraft: 'सेवेतील विमाने',
      icg: 'तटरक्षक जहाजे',
      indigenous: '% स्वदेशी ताफा',
      shipyards: 'सक्रिय जहाज कारखाने',
      projects: 'चालू प्रकल्प',
    },
    aatmanirbharTitle: 'आत्मनिर्भर भारत —',
    aatmanirbharTitleHighlight: 'निर्माणकर्त्याचे नौदल',
    aatmanirbharSubtitle: 'जून 2026 महत्त्वाचा टप्पा',
    aatmanirbharDesc: 'जून 2026 पर्यंत, भारतीय नौदल खऱ्या अर्थाने \'निर्माणकर्त्याचे नौदल\' बनले आहे। ताफ्यातील विक्रमी 67% आता स्वदेशी बांधणीचे आहे, 8 जहाज कारखान्यांमध्ये 56 युद्धनौका बांधणी प्रकल्प सुरू आहेत।',
    tripleCommission: 'त्रिविध कमिशनिंग — 21 जून 2026',
    tripleCommissionDesc: 'एकाच समारंभात तीन प्रमुख युद्धनौका कमिशन: INS दुनागिरी, INS अग्रे, आणि INS संशोधक।',
    historicTitle: 'ऐतिहासिक ताफा',
    historicSubtitle: 'ज्यांनी नौदल घडवले ते दिग्गज।',
    exploreTitle: 'भारतीय नौदल ताफा',
    exploreSubtitle: 'भारतीय नौदल आणि तटरक्षक दलाचा संपूर्ण ऑर्डर ऑफ बॅटल ब्राउझ करा।',
    searchPlaceholder: 'नाव, वर्ग किंवा प्रकल्पानुसार शोधा...',
    viewDetails: 'तपशील पहा',
    commissioned: 'कमिशन',
    decommissioned: 'सेवामुक्त',
    status: 'स्थिती',
    active: 'सक्रिय',
    decommissionedStatus: 'सेवामुक्त',
    category: 'श्रेणी',
    class: 'वर्ग',
    project: 'प्रकल्प',
    builder: 'बांधणीदार',
    origin: 'मूळ',
    fleet: 'ताफा',
    homePort: 'गृह बंदर',
    technicalSpecs: 'तांत्रिक वैशिष्ट्ये',
    displacement: 'विस्थापन',
    length: 'लांबी',
    beam: 'रुंदी',
    draft: 'खोली',
    speed: 'कमाल वेग',
    range: 'परास',
    crew: 'चालक दल',
    propulsion: 'प्रणोदन',
    armament: 'शस्त्रास्त्रे',
    aircraft: 'विमाने',
    sensors: 'सेन्सर',
    operationalHistory: 'परिचालन इतिहास',
    watchVideo: 'व्हिडिओ पहा',
    backToFleet: 'ताफ्याकडे परत',
    noResults: 'या फिल्टरसाठी कोणतीही मालमत्ता आढळली नाही।',
    footerTagline: 'भारतीय नौदल ट्रॅकिंग — जय हिंद!',
    navExplore: 'ताफा एक्सप्लोर',
    navHistoric: 'ऐतिहासिक',
    navAbout: 'बद्दल',
    pennant: 'पेनेंट',
    navHome: 'होम',
    officialSite: 'अधिकृत साइट',
    orderOfBattle: 'भारतीय नौदल ऑर्डर ऑफ बॅटल',
    exploreFleet: 'ताफा पहा',
    scroll: 'स्क्रोल',
    aboutEyebrow: 'भारतीय नौदलाबद्दल',
    aboutTitle: 'समुद्रातील शक्ती,',
    aboutTitleHighlight: 'राष्ट्राचा अभिमान',
    aboutPara1: 'भारतीय नौदल हे भारतीय सशस्त्र दलांची सागरी शाखा आहे. 17व्या शतकातील मराठा नौदलाच्या वारशातून विकसित होत ते आज एक सक्षम ब्लू-वॉटर नौदल बनले आहे.',
    aboutPara2: 'नवी दिल्ली येथे मुख्यालय असलेले नौदल पश्चिम, पूर्व आणि दक्षिण अशा तीन कमांडद्वारे भारताच्या विशाल सागरी हितांचे संरक्षण करते.',
    aboutPara3Prefix: 'अंतर्गत',
    aboutPara3Strong: 'आत्मनिर्भर भारत',
    aboutPara3Suffix: 'उपक्रमामुळे भारत स्वदेशी विमानवाहू जहाजे, विध्वंसक, फ्रिगेट्स आणि पाणबुड्या तयार करणारे महत्त्वाचे नौदल उत्पादन केंद्र बनत आहे.',
    officialNavyWebsite: 'भारतीय नौदलाची अधिकृत वेबसाइट',
    browseFleet: 'ताफा ब्राउझ करा',
    legacyHeritage: 'वारसा आणि इतिहास',
    viewAllHistoricAssets: 'सर्व ऐतिहासिक मालमत्ता पहा',
    pillars: {
      maritimeTitle: 'सागरी सुरक्षा',
      maritimeDesc: 'भारतीय महासागर क्षेत्रातील 7,500 किमीपेक्षा जास्त किनारपट्टी आणि विशाल विशेष आर्थिक क्षेत्राचे संरक्षण.',
      powerTitle: 'शक्ती प्रदर्शन',
      powerDesc: 'विमानवाहू जहाजे, अण्वस्त्र पाणबुड्या आणि आधुनिक पृष्ठभाग ताफ्यासह मजबूत ब्लू-वॉटर क्षमता.',
      selfRelianceTitle: 'आत्मनिर्भर भारत',
      selfRelianceDesc: 'ताफ्याचा मोठा भाग स्वदेशी बांधणीचा असून अनेक युद्धनौका प्रकल्प सक्रिय जहाज कारखान्यांत सुरू आहेत.',
      humanitarianTitle: 'मानवीय अभियान',
      humanitarianDesc: 'आपत्ती मदतीपासून अँटी-पायरेसी गस्तपर्यंत, नौदल युद्धापलीकडेही सेवा करते.',
    },
    categoryLabels: {
      all: 'सर्व मालमत्ता',
      carriers: 'विमानवाहू जहाजे',
      destroyers: 'विध्वंसक',
      frigates: 'फ्रिगेट्स',
      corvettes: 'कॉर्वेट्स आणि ASW',
      submarines: 'पाणबुड्या',
      amphibious: 'उभयचर',
      icg: 'तटरक्षक',
      mpv: 'MPV आणि सपोर्ट',
      survey: 'सर्वे आणि पुनर्भरण',
      historic: 'ऐतिहासिक ताफा',
    },
    assetCountSingular: 'मालमत्ता',
    assetCountPlural: 'मालमत्ता',
    resultsFor: 'परिणाम',
    tryDifferentFilter: 'कृपया वेगळी श्रेणी किंवा शोध शब्द वापरा.',
    clearFilters: 'फिल्टर साफ करा',
    assetNotFound: 'मालमत्ता सापडली नाही',
    returnToFleet: 'ताफ्याकडे परत जा',
    imageGallery: 'चित्र गॅलरी',
    officialVideo: 'अधिकृत व्हिडिओ',
    relatedAssets: 'संबंधित मालमत्ता',
    speedLabel: 'वेग',
    crewLabel: 'दल',
    navFooterTitle: 'नेव्हिगेशन',
    dataSources: 'डेटा स्रोत',
    home: 'होम',
    publicData: 'सार्वजनिक आणि ओपन-सोर्स डेटा',
    dataCurrent: 'डेटा जून 2026 पर्यंत अद्ययावत',
    footerDescription: 'भारतीय नौदल मालमत्तांचा — युद्धनौका, पाणबुड्या, विमाने आणि ऐतिहासिक जहाजे — संदर्भ डेटाबेस.',
    footerLegal: 'फक्त शैक्षणिक आणि संदर्भ वापरासाठी. भारतीय नौदलाशी संलग्न नाही.',
    fleetOperational: 'ताफा परिचालनात',
  },
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem('varuna-lang') || 'en');
  const t = translations[lang];

  useEffect(() => {
    localStorage.setItem('varuna-lang', lang);
    document.documentElement.lang = lang;
  }, [lang]);

  return (
    <LanguageContext.Provider value={{ lang, setLang, t, translations }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
}

export default LanguageContext;
